version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - base_network
  migrations:
    build: .
    env_file: .env
    command: poetry run python manage.py migrate
    networks:
      - base_network
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: python manage.py runserver
    networks:
      - base_network
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

networks:
  base_network:
volumes:
  postgres_data:

