# Generated by Django 5.1 on 2024-09-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField(null=True)),
                ('date_time', models.DateTimeField(null=True)),
                ('http_method', models.TextField(null=True)),
                ('uri', models.TextField(null=True)),
                ('response_code', models.TextField(null=True)),
                ('response_size', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'LogsInfo',
            },
        ),
    ]
